### ISSUE TITLE
Cantidad de items a mostrar por pagina

### ISSUE THREAD

**Issue by ccaraccio** [reyesdiego/TerminalsUI#193]
Se sugiere cambiar el combo que contiene la cantidad de elementos a mostrar (dentro de comprobantes), al final de la pagina, entre la tabla y los numeros del paginado.

**Comment by tioma** [comment]
Este cambio rompería varias directivas del proyecto, teniendo gran repercusión en el código de casi todas las vistas, algo innecesario por algo que es meramente subjetivo.
