### ISSUE TITLE
Comprobante con matcheo incongruente

### ISSUE THREAD

**Issue by ccaraccio** [reyesdiego/TerminalsUI#206]
El comprobante 158018 del punto de venta 24 con fecha 16-1-2015 cobra un item con codigo 1465 denominado "Tasa a las cargas. Carga General. Importacion" y cobra un precio de U$S 0.75 por TN. Dicho precio pertenece a Removidos y no a Importacion. En este último caso, el costo a cobrar deberia ser : U$S 4

**Comment by ccaraccio** [comment]
Terminal: BACTSSA

**Comment by tioma** [comment]
El control de códigos fue actualizado para que además verifique este tipo de tarifas, de modo que en cuanto a tasas a las cargas se cobre justo el monto especificado.
