### ISSUE TITLE
Error no capturado al ver comprobante

### ISSUE THREAD

**Issue by ccaraccio** [reyesdiego/TerminalsUI#213]
El error se produce al intentar ver el comproabnte N°2 del dia:9/12/2014 Pto Vta:60 Terminal : TRP
Se ha producido un error inesperado: ReferenceError: trackingInvoiceCtrl is not defined

**Comment by leoguty91** [comment]
El error no se puede reproducir cuando se utiliza la versión de Desarrollo, habrá que actualizar la versión de Testing
