### ISSUE TITLE
Controlar comprobantes

### ISSUE THREAD

**Issue by ccaraccio** [reyesdiego/TerminalsUI#228]
Al querer controlar un comprobante especifico por numero, el sistema arroja el siguiente error TypeError: $scope.todosLosPuntosDeVentas[0] is undefined . Eso se corrige eligiendo correctamente la fecha del comprobante que se quiere controlar. 
El mensaje de error deberia ser mas amigables

**Comment by tioma** [comment]
No se pudo reproducir el error

**Comment by tioma** [comment]
El manejo de errores se modificó para mostrar mensajes más amigables.
